### ISSUE TITLE
[user experience] issues downloading docker images

### ISSUE THREAD

**Issue by sjiekak** [camunda/zeebe-benchmark-helm#247]
As an user not part of the zeebe team
I had trouble downloading docker images. 
First I did not have the permissions. 

Then still `ImagePullBackoff` errors.
I had to set a specific tag

```
  image:
    # Image.repository defines the repository from which to fetch the docker images
    repository: "gcr.io/zeebe-io"
    # Image.tag defines the tag / version which should be used in the chart
    tag: 8.8.0-SNAPSHOT-main-c3674312
    ## @param global.image.pullPolicy defines the image pull policy which should be used https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy
    pullPolicy: IfNotPresent
```

then load into my kubernetes context manually (it was `kind`)
